language: c

git:
  depth: 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8-multilib
      - linux-libc-dev
      - linux-libc-dev:i386

env:
  global:
    - DEPLOY_LIBS="libED_CSVFile.a libED_INIFile.a libED_JSONFile.a libED_MATFile.a libED_XLSFile.a libED_XLSXFile.a libED_XMLFile.a libED_XML2File.a libbsxml-json.a libexpat.a libminizip.a libparson.a libxml2.a libxlsreader.a libzlib.a"
    # BBPASS
    - secure: "UliVEFl4G/G2/Zvje6mjN8PjWVOhUjwZPYDki+APtTNLs8/00Mp0cOBuFEuB1mbRJ7aUNtNnbg54V/BGlSxgzDfiwhWSSxPiJFPQSmNJdhXJS7oWLl7dCVxzd6NFNiRZfCKxR5lR/y16Svt4Nek7ANHJru+lzWuRwJK6DJDSsY2eTu5ab/idkALxsYI/bsr/SbLhoi5TWbrpzabxgB2P2oYKKH07jgmu3XYIyqJTctvfGRCBGUTYIOM3XGizNIm50kUPqmPAiDpuKcbQyLhENoL8vttI1DBdUDgiFy6seu20f/P+SsrujHkFo7zrcyAm70YeIG+RhLkBKXoWZ4xd4SMnojrR+gySoiMbNO7ENkTH15IzLZNe7zrwhInDmm3buOO2s2eKWhjvBJZDr3OGMzwUk3ceLuofcNTxeC6tBomkGVz4Q6MWkLlqJ2qxQtHFd/1SRJl2d5QtHoRFUplP/idx04IQcXFlR770RtUCzspkPAdGS4pbe1pUxqdPjky9EIVcyGwLEeBH9uA/fPRwxN9BdUSnq8Jlk294Lx349mv8cIh1frdou/YIOQDTeGaGPrXHyz4RyXVq5W1Ih7WeF2iBIAXldlhIRKZPT0t58S/z/51eB9w8HUCtrgrTYBQLAiQUJYN+RcXoZLVPWEw+N/rdW5MVDFq9QBYVDnX27rQ="

matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      env:
        - PLATFORM=linux32
        - CFLAGS="-O3 -DNDEBUG -fPIC -msse2 -m32"
        - CXXFLAGS="-O3 -DNDEBUG -fPIC -msse2 -m32"
        - CMAKE=/opt/cmake-3.18.6-Linux-x86_64/bin/cmake
        - TARGETDIR="linux32"
        - GM="Unix Makefiles"
        - MAKE=make
    - os: linux
      compiler: gcc-4.8
      env:
        - PLATFORM=linux64
        - CFLAGS="-O3 -DNDEBUG -fPIC"
        - CXXFLAGS="-O3 -DNDEBUG -fPIC"
        - CMAKE=/opt/cmake-3.18.6-Linux-x86_64/bin/cmake
        - TARGETDIR="linux64"
        - GM="Unix Makefiles"
        - MAKE=make
    - os: linux
      compiler: clang
      env:
        - PLATFORM=linux64
        - CFLAGS="-O3 -DNDEBUG -fPIC"
        - CXXFLAGS="-O3 -DNDEBUG -fPIC"
        - CMAKE=/opt/cmake-3.18.6-Linux-x86_64/bin/cmake
        - TARGETDIR="linux64"
        - GM="Unix Makefiles"
        - MAKE=make
    - os: osx
      compiler: gcc
      env:
        - PLATFORM=darwin64
        - CC=gcc
        - CMAKE=cmake
        - TARGETDIR="darwin64"
        - GM="Unix Makefiles"
        - MAKE=make
    - os: windows
      compiler: gcc
      env:
        - PLATFORM=mingw32
        - CC=gcc
        - CMAKE=cmake
        - TARGETDIR="mingw32"
        - GM="MinGW Makefiles"
        - MAKE=mingw32-make
    - os: windows
      compiler: gcc
      env:
        - PLATFORM=mingw64
        - CC=gcc
        - CMAKE=cmake
        - TARGETDIR="mingw64"
        - GM="MinGW Makefiles"
        - MAKE=mingw32-make

before_install:
  - |-
    case $TRAVIS_OS_NAME in
      linux)
        curl -sSL https://cmake.org/files/v3.18/cmake-3.18.6-Linux-x86_64.tar.gz | sudo tar -xzC /opt
        ;;
      osx)
        ## do not update, it seems to just waste resources and is never able to finish
        ## brew update
        ;;
      windows)
        ## mostly from here: https://docs.travis-ci.com/user/reference/windows/
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        ## 32bit mingw
        export mingw32="$msys2 -mingw32 -full-path -here -c "\"\$@"\" --"
        ## 64bit mingw
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-{i686,x86_64}-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        $msys2 pacman --sync --noconfirm --needed autoconf autoconf-archive automake automake-wrapper binutils gettext git libtool m4 make pkg-config mingw-w64-{i686,x86_64}-clang mingw-w64-{i686,x86_64}-make mingw-w64-{i686,x86_64}-cmake mingw-w64-{i686,x86_64}-extra-cmake-modules mingw-w64-{i686,x86_64}-{gcc,binutils} mingw-w64-{i686,x86_64}-hdf5
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac
  - curl https://bitbucket.org/Swyter/bitbucket-curl-upload-to-repo-downloads/raw/default/upload-to-bitbucket.sh -O -J -L
  - chmod +x ./upload-to-bitbucket.sh
  - git clone --branch v2.13.5 --depth 1 https://gitlab.gnome.org/GNOME/libxml2
  - mkdir -p libxml2/$PLATFORM

before_cache:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
  directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$PLATFORM" == "linux32" ]]; then ./.CI/travis_script.sh CFLAGS="-O3 -msse2 -m32 -fPIC"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$PLATFORM" == "linux64" ]]; then ./.CI/travis_script.sh CFLAGS="-O3 -fPIC"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./.CI/travis_script.sh CFLAGS="-O3"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] && [[ "$PLATFORM" == "mingw32" ]]; then $mingw32 ./.CI/travis_script.sh CFLAGS="-O3"; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]] && [[ "$PLATFORM" == "mingw64" ]]; then $mingw64 ./.CI/travis_script.sh CFLAGS="-O3"; fi

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]] || [[ "$TRAVIS_BRANCH" != "master" ]]; then exit 0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CC" == "gcc-4.8" ]]; then sh ./upload-to-bitbucket.sh tbeu $BBPASS /tbeu/downloads/downloads ExternData_$PLATFORM.tar.xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./upload-to-bitbucket.sh tbeu $BBPASS /tbeu/downloads/downloads ExternData_$PLATFORM.tar.xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then $msys2 curl -k --progress-bar -o nul -L -f -u "tbeu:$BBPASS" -F files=@"ExternData_$PLATFORM.tar.xz" "https://api.bitbucket.org/2.0/repositories/tbeu/downloads/downloads"; fi

notifications:
  email: false
